### ISSUE TITLE
Checking DB connectivity as root might not be correct

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_store#33]
https://github.com/FNNDSC/ChRIS_store/blob/7b3c58b14e738c0537f9060b65dc1c9a323bc207/docker-entrypoint.sh#L3

I'm in an esoteric situation, trying to migrate the backend for https://chrisstore.co

The MySQL database was seemingly successfully migrated using `mysqldump` and as you can see, the backend is working

```
https://chrisstore.co/api/v1/plugins/1/
```

However I noticed that `python check_db_connection.py` fails --- which might be expected since by default, MySQL does not permit root login from non-localhost. Regardless there is no effect if the command is unsuccessful.

**Comment by jbernal0019** [comment]
This has been fixed with the upgrade to Postgres 13.
