### ISSUE TITLE
Implement category functionality for plugins

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_store#43]
There are many plugins that could be listed in the ChRIS store that could qualify as being under multiple categories. It would then make sense to implement the Categories as being tag style, where any given plugin could be a member of more than one category at once.

See discussion here https://github.com/FNNDSC/ChRIS_store_ui/pull/124#issuecomment-818983651  (and elsewhere)

**Comment by EUGINELETHAL** [comment]
@mairin are the tags created only by the superuser or when a user submits a plugin he/she can also create a tag if not available

**Comment by jennydaman** [comment]
@mairin @jbernal0019 should we modify categories to work like tags, or should we have both categories and tags? I think the 1-1 categories has some usefulness, albeit limited. However, it'd be easier to add a new feature than to change an existing one.

**Comment by mairin** [comment]
@jennydaman I'd add it new if it's easier.

@EUGINELETHAL I think the tags should be creatable / editable / removable by the superuser and by anyone with ownership of the plugin. I don't think it should be open to the general public / any user. (What do you think @jennydaman / @jbernal0019 ?)

**Comment by mairin** [comment]
Deprecating this issue for https://github.com/FNNDSC/ChRIS_store/issues/42
